numpy abd pandas


In [1]:
##Numpy->Play with arrays (numbers)
##pandas->dataset
##matplotlib->data visualization
##seaborn->data visualization
##


In [2]:
import numpy as np


In [3]:
simple_list=[86,87,88]
np.array(simple_list)

array([86, 87, 88])

In [4]:
arr=np.array([4,5,6])
arr

array([4, 5, 6])

In [6]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(8,28)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27])

In [8]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
np.arange(1,25,4)#shift+tab->help box

array([ 1,  5,  9, 13, 17, 21])

In [11]:
np.arange(1,25,5)

array([ 1,  6, 11, 16, 21])

In [12]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(8,int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((5,3),int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [22]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.ones((5,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.linspace(2,5,3)

array([2. , 3.5, 5. ])

In [26]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
np.eye((5),dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [28]:
np.random.rand(3,5)

array([[0.66994607, 0.24495596, 0.23401713, 0.40674914, 0.57197664],
       [0.5741393 , 0.81879183, 0.17113469, 0.77785606, 0.85422394],
       [0.41008868, 0.32551693, 0.14227712, 0.24624019, 0.44739236]])

In [29]:
np.random.randn(3,5)

array([[-0.1378635 ,  0.79377387, -0.93779232,  0.15737607,  1.02388006],
       [-1.68888341,  0.37123584,  0.82783665,  1.20040042, -2.60177018],
       [-0.20615225,  1.68701047,  0.67919853, -1.5051754 ,  0.76341295]])

In [30]:
np.random.randint(2,10)

5

In [33]:
np.random.randint(2,10,2)

array([7, 4])

In [32]:
np.random.randint(20,30,100)

array([23, 28, 26, 21, 26, 29, 23, 20, 22, 22, 27, 27, 20, 21, 23, 23, 21,
       27, 28, 28, 26, 20, 25, 20, 22, 20, 20, 26, 24, 22, 22, 22, 23, 27,
       23, 20, 25, 28, 29, 25, 28, 21, 26, 26, 28, 23, 25, 21, 28, 29, 26,
       23, 22, 21, 24, 28, 20, 29, 27, 29, 27, 20, 25, 22, 24, 29, 26, 20,
       20, 28, 22, 28, 24, 20, 28, 25, 29, 29, 20, 21, 23, 29, 21, 29, 22,
       22, 25, 29, 23, 27, 27, 22, 26, 24, 27, 29, 22, 24, 25, 26])

In [35]:
sample_array=np.arange(20)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
rand_array=np.random.randint(10,50,50)
rand_array

array([47, 36, 11, 11, 10, 38, 39, 22, 47, 35, 37, 23, 14, 35, 47, 14, 15,
       17, 33, 44, 36, 13, 34, 17, 27, 49, 10, 41, 11, 10, 37, 16, 18, 20,
       49, 47, 15, 39, 37, 46, 16, 15, 46, 35, 31, 22, 31, 45, 20, 44])

In [39]:
sample_array.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [40]:
sample_array.reshape(5,3)

ValueError: cannot reshape array of size 20 into shape (5,3)

In [41]:
rand_array.max()

49

In [42]:
rand_array.min()

10

In [43]:
rand_array.argmax()

25

In [45]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
a=np.random.rand(2,3)

In [49]:
a

array([[0.8213733 , 0.13021675, 0.41143094],
       [0.00966621, 0.07573091, 0.79223213]])

In [50]:
a.T

array([[0.8213733 , 0.00966621],
       [0.13021675, 0.07573091],
       [0.41143094, 0.79223213]])

In [51]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
sample_array[0]

10

In [54]:
sample_array[5:9]

array([15, 16, 17, 18])

In [55]:
sample_array[2:6]=50
sample_array

array([10, 11, 50, 50, 50, 50, 16, 17, 18, 19, 20])

In [57]:
sample_array[:]=100
sample_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [58]:
sub_set=np.sample_array
sub_set

SyntaxError: invalid syntax (2982598711.py, line 1)

In [59]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [61]:
subset_sample_array=sample_array[0:7]

In [62]:
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])